### ISSUE TITLE
not all images are labeled in folder "2011_09_28"

### ISSUE THREAD

**Issue by linbaiwpi** [TWJianNuo/EdgeDepth-Release#9]
Hi, first thanks for your great work. But I notice that in the semantic labels you supplied, only two subfolders are labeled. So during training, you guys are only use this incomplete dataset?

**Comment by TWJianNuo** [comment]
Correct. I did not generate for the whole kitt dataset but the images have coverred every one of eigen training/validation/testing splits.The real reason is I downloaded the kitti raw dataset using scripts from github repo "Monodepth2" and did not notice they only include part of kitti dataset(that is good since it can save space). Anyway, I probably will update a full version in the future, will let you know if that happen.

**Comment by linbaiwpi** [comment]
> Correct. I did not generate for the whole kitt dataset but the images have coverred every one of eigen training/validation/testing splits.The real reason is I downloaded the kitti raw dataset using scripts from github repo "Monodepth2" and did not notice they only include part of kitti dataset(that is good since it can save space). Anyway, I probably will update a full version in the future, will let you know if that happen.

Thank you for your patient explanation. I'll close this issue.
